name: variables and secrets

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say $greet $person1"
        run: echo "$greet $person1. Today is $DAY_OF_WEEK!"
      - name: "Say $greet $person2 it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$greet $person2. Today is $DAY_OF_WEEK!"
      - name: "Say $greet $person3 it's Tuesday"
        if: ${{ env.DAY_OF_WEEK == 'Tuesday' }}
        run: echo "$greet $person3. Today is $DAY_OF_WEEK!"